export const heroes = [
  {
    name: 'Abaddon',
    class: 'Boss',
    faction: 'Demons',
    brotherhood: ['Abyss Slaves'],
  },
  {
    name: 'Abyss Hound',
    class: 'Melee Damager',
    faction: 'Demons',
    brotherhood: ['Group of Villains'],
  },
  {
    name: 'Aegnor',
    class: 'Melee Damager',
    faction: 'Wild Elves',
    brotherhood: ['Mercenaries'],
  },
  {
    name: 'Arekhon Axe Thrower',
    class: 'Ranged Damager',
    faction: 'Arekhon Undead',
    brotherhood: ['Mercenaries'],
  },
  {
    name: 'Arekhon Guard',
    class: 'Tank',
    faction: 'Arekhon Undead',
    brotherhood: [null],
  },
  {
    name: 'Arekhon Shadow',
    class: 'Rogue',
    faction: 'Arekhon Undead',
    brotherhood: ['Mercenaries', 'Group of Villains'],
  },
  {
    name: 'Arekhon Spear',
    class: 'Melee Damager',
    faction: 'Arekhon Undead',
    brotherhood: [null],
  },
  {
    name: 'Argen',
    class: 'Rogue',
    faction: 'Archons',
    brotherhood: [null],
  },
  {
    name: 'Arkhane',
    class: 'Caster',
    faction: 'Orks',
    brotherhood: [null],
  },
  {
    name: 'Artar',
    class: 'Melee Damager',
    faction: 'Barbarians',
    brotherhood: ['Mercenaries', 'Retribution Squad', 'Lost Allies'],
  },
  {
    name: 'Artus',
    class: 'Boss',
    faction: 'Archons',
    brotherhood: [null],
  },
  {
    name: 'Atiles',
    class: 'Tank',
    faction: 'Barbarians',
    brotherhood: ['Roland Allies', 'Retribution Squad'],
  },
  {
    name: 'Azariel',
    class: 'Healer',
    faction: 'Dark Elves',
    brotherhood: [null],
  },
  {
    name: 'Balthazar',
    class: 'Caster',
    faction: 'Renegades',
    brotherhood: ['Abyss Slaves'],
  },
  {
    name: 'Bellara',
    class: 'Caster',
    faction: 'Barbarians',
    brotherhood: ['Forest Shamans', 'Retribution Squad', 'Roland Allies'],
  },
  // {
  //   name: 'Beorn',
  //   class: 'Boss',
  //   faction: 'Children of the Forest',
  //   brotherhood: [null],
  //
  // },
  {
    name: 'Blood Emperor',
    class: 'Boss',
    faction: 'Arekhon Undead',
    brotherhood: [null],
  },
  {
    name: 'Blood Mage',
    class: 'Caster',
    faction: 'Arekhon Undead',
    brotherhood: ['Group of Villains'],
  },
  {
    name: 'Blood Priest',
    class: 'Healer',
    faction: 'Arekhon Undead',
    brotherhood: ['Group of Villains'],
  },
  {
    name: 'Cathbad',
    class: 'Healer',
    faction: 'Druids',
    brotherhood: [
      'Keepers of Arrat',
      'Forest Shamans',
      'Retribution Squad',
      'Woodland Guardians',
      'Roland Allies',
    ],
  },
  {
    name: 'Cerunol',
    class: 'Tank',
    faction: 'Wild Elves',
    brotherhood: [null],
  },
  // {
  //   name: 'Da`Ghan',
  //   class: 'Healer',
  //   faction: 'Orks',
  //   brotherhood: [null],
  //
  // },
  {
    name: 'Daimyo',
    class: 'Boss',
    faction: 'High Elves',
    brotherhood: [null],
  },
  {
    name: 'Denaya',
    class: 'Boss',
    faction: 'Barbarians',
    brotherhood: ['Retribution Squad', 'Mercenaries'],
  },
  {
    name: 'Dexxa',
    class: 'Rogue',
    faction: 'Dragonkin',
    brotherhood: ['Warriors of Light'],
  },
  // {
  //   name: 'Dragonkir',
  //   class: 'Boss',
  //   faction: 'Dragonkin',
  //   brotherhood: ['Warriors of Light'],
  //
  // },
  {
    name: 'Drake',
    class: 'Tank',
    faction: 'Dark Elves',
    brotherhood: [null],
  },
  {
    name: 'Dreverad',
    class: 'Tank',
    faction: 'Dark Elves',
    brotherhood: [
      'Keepers of Arrat',
      'Retribution Squad',
      'Woodland Guardians',
    ],
  },
  {
    name: 'Elios',
    class: 'Caster',
    faction: 'Archons',
    brotherhood: ['Warriors of Light'],
  },
  {
    name: 'Eraser',
    class: 'Caster',
    faction: 'Demons',
    brotherhood: ['Group of Villains'],
  },
  {
    name: 'Firar',
    class: 'Caster',
    faction: 'Dragonkin',
    brotherhood: ['Warriors of Light'],
  },
  {
    name: 'Fullmetal Goon',
    class: 'Tank',
    faction: 'Goblins',
    brotherhood: ['Brawlers'],
  },
  {
    name: 'Gassar',
    class: 'Rogue',
    faction: 'Dwarves',
    brotherhood: [null],
  },
  {
    name: 'Gatekeeper',
    class: 'Tank',
    faction: 'Demons',
    brotherhood: [null],
  },
  {
    name: 'Gloriana',
    class: 'Healear',
    faction: 'Wild Elves',
    brotherhood: [null],
  },
  {
    name: 'Goblinia Sweetvoice',
    class: 'Healear',
    faction: 'Goblins',
    brotherhood: ['Brawlers'],
  },
  {
    name: 'Goblinusus The Great',
    class: 'Boss',
    faction: 'Goblins',
    brotherhood: ['Brawlers'],
  },
  {
    name: 'Grok',
    class: 'Tank',
    faction: 'Kobolds',
    brotherhood: [null],
  },
  {
    name: 'Hargrim',
    class: 'Healer',
    faction: 'Dwarves',
    brotherhood: [null],
  },
  {
    name: 'Hilia',
    class: 'Healer',
    faction: 'Ra`Archne',
    brotherhood: ['Group of Villains'],
  },
  {
    name: 'Hotei',
    class: 'Healer',
    faction: 'High Elves',
    brotherhood: [null],
  },
  {
    name: 'Idrill',
    class: 'Caster',
    faction: 'Wild Elves',
    brotherhood: [null],
  },
  {
    name: 'Infernus',
    class: 'Ranged Damager',
    faction: 'Demons',
    brotherhood: [null],
  },
  {
    name: 'Irma',
    class: 'Ranged Damager',
    faction: 'Druids',
    brotherhood: ['Brawlers'],
  },
  {
    name: 'Jagg',
    class: 'Melee Damager',
    faction: 'Kobolds',
    brotherhood: ['Mercenaries', 'Group of Villains'],
  },
  // {
  //   name: 'Kabuto',
  //   class: 'Tank',
  //   faction: 'High Elves',
  //   brotherhood: [null],
  //
  // },
  {
    name: 'Kage',
    class: 'Rogue',
    faction: 'High Elves',
    brotherhood: ['Abyss Slaves'],
  },
  {
    name: 'Katar',
    class: 'Melee Damager',
    faction: 'Dragonkin',
    brotherhood: ['Warriors of Light'],
  },
  {
    name: 'Kharannah',
    class: 'Healer',
    faction: 'Dragonkin',
    brotherhood: [
      'Forest Shamans',
      'Retribution Squad',
      'Warriors of Light',
      'Roland Allies',
    ],
  },
  {
    name: 'Khshaat',
    class: 'Caster',
    faction: 'Ra`Archne',
    brotherhood: ['Group of Villains'],
  },
  {
    name: 'Kobolock',
    class: 'Healer',
    faction: 'Kobolds',
    brotherhood: [null],
  },
  {
    name: 'Kromme',
    class: 'Rogue',
    faction: 'Orks',
    brotherhood: ['Brawlers'],
  },
  {
    name: 'Las`Khary',
    class: 'Melee Damager',
    faction: 'Orks',
    brotherhood: [null],
  },
  {
    name: 'Llael',
    class: 'Rogue',
    faction: 'Dark Elves',
    brotherhood: [null],
  },
  {
    name: 'Lucky',
    class: 'Healer',
    faction: 'Children of the Forest',
    brotherhood: ['Retribution Squad', 'Keepers of Arrat', 'Brawlers'],
  },
  {
    name: 'Lokhir',
    class: 'Caster',
    faction: 'Dark Elves',
    brotherhood: [null],
  },
  {
    name: 'Maebd',
    class: 'Rogue',
    faction: 'Druids',
    brotherhood: ['Brawlers'],
  },
  {
    name: 'Maeglin',
    class: 'Rogue',
    faction: 'Wild Elves',
    brotherhood: [null],
  },
  {
    name: 'Magnus',
    class: 'Tank',
    faction: 'Archons',
    brotherhood: [null],
  },
  {
    name: 'Mizuhiko',
    class: 'Caster',
    faction: 'High Elves',
    brotherhood: [null],
  },
  {
    name: 'Myrddin',
    class: 'Caster',
    faction: 'Druids',
    brotherhood: ['Keepers of Arrat', 'Retribution Squad'],
  },
  {
    name: 'Naja',
    class: 'Boss',
    faction: 'Dark Elves',
    brotherhood: [null],
  },
  {
    name: 'Orihime',
    class: 'Ranged Damager',
    faction: 'High Elves',
    brotherhood: [null],
  },
  {
    name: 'Phoenix',
    class: 'Healer',
    faction: 'Beastmen',
    brotherhood: [null],
  },
  {
    name: 'Pride',
    class: 'Tank',
    faction: 'Children of the Forest',
    brotherhood: ['Woodland Guardians'],
  },
  {
    name: 'Prook Greasyhair',
    class: 'Melee Damager',
    faction: 'Goblins',
    brotherhood: ['Brawlers'],
  },
  {
    name: 'Raarspit',
    class: 'Ranged Damager',
    faction: 'Ra`Archne',
    brotherhood: ['Group of Villains'],
  },
  {
    name: 'Rizer',
    class: 'Rogue',
    faction: 'Ra`Archne',
    brotherhood: [null],
  },
  {
    name: 'Rogar',
    class: 'Tank',
    faction: 'Dragonkin',
    brotherhood: [
      'Mercenaries',
      'Retribution Squad',
      'Warriors of Light',
      'Roland Allies',
      'Lost Allies',
    ],
  },
  {
    name: 'Roinar',
    class: 'Melee Damager',
    faction: 'Dark Elves',
    brotherhood: ['Harbringers of Dawn'],
  },
  {
    name: 'Rok',
    class: 'Caster',
    faction: 'Beastmen',
    brotherhood: ['Abyss Slaves'],
  },
  {
    name: 'Rok`Khan',
    class: 'Tank',
    faction: 'Brawlers',
    brotherhood: [null],
  },
  {
    name: 'Roland',
    class: 'Boss',
    faction: 'Knights of the Council',
    brotherhood: [null],
  },
  {
    name: 'Sabertooth',
    class: 'Melee Damager',
    faction: 'Children of the Forest',
    brotherhood: ['Keepers of Arrat', 'Retribution Squad'],
  },
  {
    name: 'Sacrif',
    class: 'Healer',
    faction: 'Archons',
    brotherhood: [null],
  },
  {
    name: 'Sandariel',
    class: 'Boss',
    faction: 'Wild Elves',
    brotherhood: ['Harbringers of Dawn'],
  },
  {
    name: 'Seven Knives',
    class: 'Ranged Damager',
    faction: 'Barbarians',
    brotherhood: [null],
  },
  {
    name: 'Sharazar',
    class: 'Rogue',
    faction: 'Changelings',
    brotherhood: [null],
  },
  // {
  //   name: 'Shni',
  //   class: 'Rogue',
  //   faction: 'Kobolds',
  //   brotherhood: [null],
  //
  // },
  {
    name: 'Siegfried',
    class: 'Tank',
    faction: 'Knights of the Council',
    brotherhood: ['Harbringers of Dawn', 'Warriors of Light'],
  },
  {
    name: 'Silver Moon',
    class: 'Healer',
    faction: 'Barbarians',
    brotherhood: ['Forest Shamans', 'Retribution Squad'],
  },
  {
    name: 'Sneaky Beaky',
    class: 'Rogue',
    faction: 'Goblins',
    brotherhood: ['Brawlers'],
  },
  {
    name: 'Softy',
    class: 'Ranged Damager',
    faction: 'Children of the Forest',
    brotherhood: ['Keepers of Arrat', 'Retribution Squad'],
  },
  {
    name: 'Soothsayer Zytima',
    class: 'Caster',
    faction: 'Kobolds',
    brotherhood: ['Group of Villains'],
  },
  {
    name: 'Stealthy',
    class: 'Rogue',
    faction: 'Children of the Forest',
    brotherhood: ['Woodland Guardians', 'Brawlers ', 'Lost Allies'],
  },
  {
    name: 'Sterus',
    class: 'Ranged Damager',
    faction: 'Archons',
    brotherhood: ['Warriors of Light'],
  },
  {
    name: 'Succubus',
    class: 'Rogue',
    faction: 'Demons',
    brotherhood: ['Abyss Slaves'],
  },
  {
    name: 'Sun Wukong',
    class: 'Boss',
    faction: 'Beastmen',
    brotherhood: [null],
  },
  {
    name: 'Swamp Killer',
    class: 'Rogue',
    faction: 'Barbarians',
    brotherhood: ['Mercenaries'],
  },
  {
    name: 'Tahit',
    class: 'Melee Damager',
    faction: 'Ra`Archne',
    brotherhood: [null],
  },
  {
    name: 'Taneda',
    class: 'Melee Damager',
    faction: 'High Elves',
    brotherhood: ['Roland Allies'],
  },
  {
    name: 'Tileana',
    class: 'Ranged Damager',
    faction: 'High Elves',
    brotherhood: ['Harbringers of Dawn'],
  },
  {
    name: 'Tiros',
    class: 'Melee Damager',
    faction: 'Archons',
    brotherhood: [null],
  },
  {
    name: 'Torak',
    class: 'Melee Damager',
    faction: 'Kobolds',
    brotherhood: ['Group of Villains'],
  },
  {
    name: 'Tricky',
    class: 'Caster',
    faction: 'Children of the Forest',
    brotherhood: ['Woodland Guardians'],
  },
  {
    name: 'Troddar',
    class: 'Tank',
    faction: 'Dwarves',
    brotherhood: [null],
  },
  {
    name: 'Trorin',
    class: 'Boss',
    faction: 'Dwarves',
    brotherhood: [null],
  },
  {
    name: 'Tsuna',
    class: 'Rogue',
    faction: 'Beastmen',
    brotherhood: ['Harbringers of Dawn', 'Brawlers'],
  },
  {
    name: 'Velundar',
    class: 'Caster',
    faction: 'Dwarves',
    brotherhood: [null],
  },
  {
    name: 'Wieland',
    class: 'Melee Damager',
    faction: 'Druids',
    brotherhood: ['Brawlers'],
  },
  {
    name: 'Wyrm Priest',
    class: 'Boss',
    faction: 'Kobolds',
    brotherhood: ['Group of Villains'],
  },
  {
    name: 'Xaart',
    class: 'Healer',
    faction: 'Demons',
    brotherhood: [null],
  },
  {
    name: 'Zhu Bajie',
    class: 'Melee Damager',
    faction: 'Beastmen',
    brotherhood: ['Mercenaries', 'Brawlers'],
  },
];

export const placeholder = [
  {
    name: 'Placeholder',
    class: 'Placeholder',
    faction: 'Placeholder',
    brotherhood: [null],
  },
  {
    name: 'Placeholder',
    class: 'Placeholder',
    faction: 'Placeholder',
    brotherhood: [null],
  },
  {
    name: 'Placeholder',
    class: 'Placeholder',
    faction: 'Placeholder',
    brotherhood: [null],
  },
  {
    name: 'Placeholder',
    class: 'Placeholder',
    faction: 'Placeholder',
    brotherhood: [null],
  },
  {
    name: 'Placeholder',
    class: 'Placeholder',
    faction: 'Placeholder',
    brotherhood: [null],
  },
];
